# Usa una imagen optimizada para Node.js
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto del servidor
EXPOSE 4002

# Comando para iniciar el backend
CMD ["npm", "run", "dev"]
