import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layout/NavBar";
import Footer from "./components/layout/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Temporal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`min-w-full ${poppins.className}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
