import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layout/NavBar";
import Footer from "./components/layout/Footer";
import React from "react";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { User } from "lucide-react";


const poppins = Poppins({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Temporal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`min-w-full ${poppins.className}`}>
        <UserProvider>
          <NavBar />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
